### ISSUE TITLE
Is it possible to mount more than one shared_dir?

### ISSUE THREAD

**Issue by flynneva** [antmicro/renode-linux-runner-action#31]
Ideally we could mount an arbitrary list of directories to the virtual runner, no?

**Comment by WiktorOgrodnik** [comment]
This is not yet possible. If you want to do it now, you have to copy everything you need into the one directory and write a script that will move the files to the right places in the emulated environment . But I think the action could do this automatically and it would be a nice addition.

**Comment by flynneva** [comment]
@WiktorOgrodnik awesome I'll see if I can figure it out and open a PR 👍

**Comment by flynneva** [comment]
@WiktorOgrodnik I [tried to implement a quick test](https://github.com/ros-drivers/usb_cam/actions/runs/4846747303/jobs/8681831669) to see if I could get [a TFTP server](https://renode.readthedocs.io/en/latest/host-integration/sharing-files.html#starting-the-tftp-server) working that would allow us to easily upload new files / folders to the virtual machine. 

```
(monitor) include @action/hifive.resc
(hifive-unleashed) emulation CreateNetworkServer "server" "192.168.100.100"
(hifive-unleashed) connector Connect server switch0
(hifive-unleashed) server StartTFTP 69
(hifive-unleashed) server.tftp ServeDirectory @/opt/ros
(hifive-unleashed) start
Starting emulation...
(hifive-unleashed) uart_connect sysbus.uart0
```

But it looks like something isnt quite right...and the error isn't really that helpful.

```
Connection closed by foreign host.
Traceback (most recent call last):
  File "/__w/_actions/flynneva/renode-linux-runner-action/31-mount-more-than-one-directory/action/run-in-renode.py", line 634, in <module>
    setup_renode()
  File "/__w/_actions/flynneva/renode-linux-runner-action/31-mount-more-than-one-directory/action/run-in-renode.py", line 495, in setup_renode
    index = child.expect_exact(["buildroot login:", "Kernel panic"],
  File "/usr/local/lib/python3.10/dist-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.10/dist-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python3.10/dist-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7fa953392140>
```

It looks like the virtual device might be running out of space....do you know how to increase the amount of memory for it?

**Comment by WiktorOgrodnik** [comment]
I will soon propose an extension to shared-dir that will allow multiple directories to be specified, with the option the to choose the target catalog as well increase filesystem size, but this has require some architectural changes from us. For now you can just copy everything to one directory for example "to-renode", and as a first renode-run command add `mkdir -p /opt/ros && mv to-renode/payload /otp/ros`.

**Comment by flynneva** [comment]
@WiktorOgrodnik I just tried your recommended workaround (copying everything to `/opt/ros` first, then just saying that is the `shared_dir` for the action. Everything seems great up until it actually runs the commands I pass in the action...where it says then the `/opt/ros` directory is not there.

https://github.com/ros-drivers/usb_cam/actions/runs/4903998291/jobs/8756757353?pr=242

Any ideas whats going on? It seems like the action is not copying the `/opt/ros` folder properly...maybe because its too large?

**Comment by WiktorOgrodnik** [comment]
This is because your files from `/opt/ros` are unpaked to the `/mnt` directory (but this path will be changed to `/home` in the next v0 release). You need something like `mkdir -p /opt/ros && mv ./* /opt/ros`  as a first `renode-run` command.
